course_math = {
    "Aide à la réussite A" : ("Aide à la réussite","GREEN"),
    "Aide à la réussite B" : ("Aide à la réussite","GREEN"),
    "Aide à la réussite C." : ("Aide à la réussite","GREEN"),
    "Aide à la réussite D." : ("Aide à la réussite", "GREEN"),
    "Calculus I" : ("Calculus I - Théorie","RED"),
    "Calculus II" : ("Calculus II","RED"),
    "Eval. continue math. élém." : ("Mathématiques élémentaires - Evaluation continue","RED"),
    "Evénement - DCOM" : ("Evénement - DCOM","GREY"),
    "Ex. approf. méthodo." : ("Mathématiques élémentaires - Exercices approfondis et méthodologie","RED"),
    "Exercices de calculus I" : ("Calculus I - Exercices","RED"),
    "Géométrie dans plan & espace" : ("Mathématiques élémentaires - Géométrie dans le plan et l'espace","RED"),
    "Inégalités" : ("Mathématiques élémentaires - Inégalités","RED"),
    "Logique" : ("Mathématiques élémentaires - Logique","RED"),
    "Mécanique - Théorie" : ("Physique générale I - Théorie","CYAN"),
    "Mécanique - travaux dirigés" : ("Physique générale I - TP","CYAN"),
    "Prog. et algo II." : ("Programmation et algorithmique II","BLUE"),
    "Programmation et algorithmiq I" : ("Programmation et algorithmique I","BLUE"),
    "Alg . lin. géom. I. C." : ("Algèbre linéaire et géométrie I", "RED"),
    "Alg. lin. et géom. I. B" : ("Algèbre linéaire et géométrie I", "RED"),
    "Alg. lin.et géom. I. A." : ("Algèbre linéaire et géométrie I", "RED"),
    "Algèbre I. A." : ("Algèbre I", "RED"),
    "Algèbre I. B." : ("Algèbre I", "RED"),
    "Analyse I (partie A)" : ("Analyse I", "RED"),
    "Analyse I B" : ("Analyse I", "RED"),
    "Elec et magnétisme - Théorie" : ("Electricité et magnétisme - Théorie", "CYAN"),
    "Electro et magné - travaux dir" : ("Electricité et magnétisme - Travaux dirigés", "CYAN"),
    "Travaux dirigés algèbre I A" : ("Côté d'algèbre I", "RED"),
    "Travaux dirigés d'algèbre I B." : ("Côté d'algèbre I", "RED"),

    "Activité promotionnelle" : ("Activité promotionnelle", "GREY"),
    "Algèbre II": ("Algèbre II", "RED"),
    "Algèbre linéaire & gaométrieII" : ("Algèbre linéaire et géométrie II", "RED"),
    "Analyse math. II (B)" : ("Analyse mathématique II", "RED"),
    "Analyse mathématique II (A)" : ("Analyse mathématique II", "RED"),
    "Bases de données I" : ("Bases de données I", "BLUE"),
    "Bases de données I (Partie A)" : ("Bases de données I", "BLUE"),
    "Bases de données I Partie B" : ("Bases de données I", "BLUE"),
    "calcul tens et rel. rest." : ("Calcul tensoriel et relativité restreinte", "CYAN"),
    "Dvlpt. dirigé par modèles" : ("Dévellopement dirigé par modèles", "BLUE"),
    "English for Science, part 1" : ("English for science","GREY"),
    "English for Science, part 2" : ("English for science","GREY"),
    "Fonct. ordinateurs" : ("Fonctionnement des ordinateurs","BLUE"),
    "Form.LaTeX" : ("Formation LaTeX", "GREY"),
    "Introd. analyse numérique" : ("Introduction à l'analyse numérique", "RED"),
    "Méca classique I" : ("Mécanique classique I", "CYAN"),
    "Modélisation logicielle" : ("Modélisation logicielle", "BLUE"),
    "Physique générale III (A)" : ("Physique Générale III", "CYAN"),
    "Program.fonct." : ("Programmation fonctionnelle", "BLUE"),
    "Prob. stat. I (A)" : ("Probabilité et statistique I", "RED"),
    "Prob. stat. I (B)" : ("Probabilité et statistique I", "RED"),
    "Projet d'informatique": ("Projet d'informatique", "BLUE"),
    "Projet de dvlpt logiciel": ("Projet de génie logiciel", "BLUE"),
    "Sém. Introd. log. math. I": ("Séminaire d'intro à la logique mathématique", "RED"),
    "Sém.Intro.logique math. II": ("Séminaire d'intro à la logique mathématique", "RED"),
    "Simulation": ("Simulation", "BLUE"),
    "Structures de données I": ("Structures de données I", "BLUE"),
    "Théorie des groupes" : ("Théorie des groupes", "CYAN"),
    "Travaux pratiques d'analyse nu": ("Travaux pratiques d'analyse numérique", "RED"),
    "Univers struct. const." : ("Univers", "CYAN"),

    "Algèbre III" : ("Algèbre III", "RED"),
    "Anal. math. III (A)" : ("Analyse mathématique III", "RED"),
    "Anal.math. III (B)" : ("Analyse mathématique III", "RED"),
    "Analyse complexe" : ("Analyse complexe", "RED"),
    "Analyse et conc des syst d'ens" : ("Analyse et conception des systèmes d'enseignement", "GREY"),
    "Bases de données II" : ("Bases de données II", "BLUE"),
    "Compilation" : ("Compilation", "BLUE"),
    "Compl de probabilités et stat" : ("Complément de probabilité et statistiques", "RED"),
    "Compléments de mathématiques" : ("Compléments de mathématiques", "CYAN"),
    "Dida ana. trans. sec-univ" : ("Didactique de l'analyse dans la transition secondaire-université", "GREY"),
    "Economie - AAEP" : ("Économie", "ORANGE"),
    "English for Sc Com part 1" : ("English for Scientific Communication", "GREY"),
    "English for Sc Com part 2" : ("English for Scientific Communication", "GREY"),
    "Etude d'obj. math élémentaire" : ("Étude d'obets de la mathématique élémentaire", "RED"),
    "Evénement - DCOM" : ("Evénement - DCOM", "GREY"),
    "Intelligence artificielle" : ("Intelligence artificielle", "BLUE"),
    "Intro à la réalité fin - AAEP" : ("Introduction à la réalité financière", "ORANGE"),
    "introd à l'util bases don math" : ("Introduction à l'utilisation de bases de données mathématiques", "GREY"),
    "Introd aux variétés différ." : ("Introduction aux variétés différentielles", "RED"),
    "Logique math." : ("Logique mathématique", "RED"),
    "Machine Learning I" : ("Machine Learning I", "BLUE"),
    "Méca. quant. applications" : ("Mécanique quantique - applications", "CYAN"),
    "Méca. quant. théorie" : ("Mécanique quantique - théorie", "CYAN"),
    "Mécanique Classique II" : ("Mécanique classique II", "CYAN"),
    "Physique atom. et molé." : ("Physique atomique et moléculaire", "CYAN"),
    "Physique nucléaire I Theorie" : ("Physique nucléaire", "CYAN"),
    "Prob. et stat. II (A)" : ("Probabilités et statistiques II", "RED"),
    "Prob. et stat. II (B)" : ("Probabilités et statistiques II", "RED"),
    "Projet de réseaux I" : ("Projet de réseaux I", "BLUE"),
    "Réseaux I" : ("Réseaux I", "BLUE"),
    "Sciences de l'éduc + formation": ("Sciences de l'éducation et de la formation", "GREY"),
    "Sém logique math I" : ("Séminaire d'introduction à la logique mathématique I", "RED"),
    "Structures de données II" : ("Structure de données II", "BLUE"),
    "Systèmes d'exploitation" : ("Systèmes d'exploitation", "BLUE"),
    "TAF - AAEP" : ("Théorie et analyse financière", "ORANGE"),
    "Théorie des modèles I" : ("Théorie des modèles", "RED"),

    "AdvDeepLearn" : ("Advanced machine learning and deep learning", "BLUE"),
    "AdvMachLearn" : ("Advanced machine learning and deep learning", "BLUE"),
    "AidMulticrDéc" : ("Aide multicritère à la décision", "BLUE"),
    "Algorithmique et bioinfo" : ("Algorithmique et bioinformatique", "BLUE"),
    "Analyse num : équations diff." : ("Projet d'analyse numérique sur les équations différentielles", "RED"),
    "AtModélRechOp" : ("Atelier de modélisation en Recherche Opérationnelle", "GREY"),
    "Calcul.et complexité" : ("Calculabilité et complexité", "BLUE"),
    "Defi IA" : ("Défi en IA", "BLUE"),
    "Dida ana. trans. sec-univ" : ("Didactique de l'analyse dans la transition secondaire-université", "GREY"),
    "Didactique math.disc.connexes" : ("Didactique des mathématiques discrètes", "RED"),
    "Entrepr, créativité - AAEP" : ("Entrepreneuriat, créativité et modèles d'affaires", "ORANGE"),
    "Entrepre., busines plan - AAEP" : ("Entrepreneuriat, business plan et plan financier", "ORANGE"),
    "Etude d'obj. math élémentaire" : ("Etude d'objets de la mathématique élémentaire", "RED"),
    "Finance d'entreprise - AAEP" : ("Finance d'entreprise", "ORANGE"),
    "Financial Markets - AAEP" : ("Financial Markets and Portfolio Management", "ORANGE"),
    "Gest de la prod et mod - AAEP" : ("Gestion de la production et modélisation", "ORANGE"),
    "Gestion financière - AAEP" : ("Gestion financière", "ORANGE"),
    "Graphes et intelligence artifi" : ("Graphes et intelligence artificielle", "BLUE"),
    "GraphOptComb" : ("Graphes et optimisation combinatoire", "BLUE"),
    "introd à l'util bases don math" : ("Introduction à l'utilisation de bases de données mathématiques", "GREY"),
    "Introduction à R" : ("Introduction à R", "BLUE"),
    "Knowledge repres.and reasoning" : ("Knowledge representation and reasoning", "BLUE"),
    "Machine Learning II" : ("Machine Learning II", "BLUE"),
    "Méth. formelles application" : ("Methode formelle - application", "RED"),
    "Méthodes formelles : Fondem." : ("Methode formelle - fondements", "RED"),
    "Méthodes formelles : intro" : ("Methode formelle - introduction", "RED"),
    "Méthodes statistiques" : ("Méthodes statistiques", "ORANGE"),
    "Models and methods in Data Sci" : ("Models and methods in Data Science", "GREY"),
    "OptimGestProd" : ("Optimisation et gestion de la production", "ORANGE"),
    "OptmLin" : ("Optimisation linéaire", "ORANGE"),
    "Produits fin. dérivés - AAEP" : ("Prouits financiers dérivés", "ORANGE"),
    "Projet d'analyse math intro" : ("Projet d'analyse mathématique - introduction", "RED"),
    "Projet d'analyse math travaux" : ("Projet d'analyse mathématique - introduction", "RED"),
    "Projet géom.alg." : ("Projet de géométrie algébrique", "RED"),
    "Projet logique math. II" : ("Projet de logique mathématique II", "RED"),
    "Projet Math. effectives" : ("Projet de mathématiques effectives", "RED"),
    "Projet prob.stat. III" : ("Projet de probabilités et statistiques III", "RED"),
    "Questions de probabilités" : ("Questions de probabilités", "RED"),
    "Réseaux II" : ("Réseaux II", "BLUE"),
    "Sém. gestion port. - AAEP" : ("Séminaire de gestion de portefeuille", "ORANGE"),
    "SéminIntArtf" : ("Séminaire Intelligence Artificielle","BLUE"),
    "Software evolution" : ("Software evolution","BLUE"),
    "StreamDatAnal" : ("Stream data analysis", "GREY")
}
