course_math = {
    "Aide à la réussite (partie A)" : "Aide à la réussite",
    "Aide à la réussite (partie B)" : "Aide à la réussite",
    "Aide à la réussite C." : "Aide à la réussite",
    "Alg . lin. géom. I. C." : "Algèbre linéaire et géométrie I",
    "Alg. lin. et géom. I. B" : "Algèbre linéaire et géométrie I",
    "Alg. lin.et géom. I. A." : "Algèbre linéaire et géométrie I",
    "Algèbre I. A." : "Algèbre I",
    "Algèbre I. B." : "Algèbre I",
    "Analyse I (partie A)" : "Analyse I",
    "Analyse I B" : "Analyse I",
    "Calculus I" : "Calculus I - Théorie",
    "Calculus II" : "Calculus II",
    "Elec et magnétisme - Théorie" : "Electricité et magnétisme - Théorie",
    "Electro et magné - travaux dir" : "Electricité et magnétisme - Travaux dirigés",
    "Eval. continue math. élém." : "Mathématiques élémentaires - Evaluation continue",
    "Evénement - DCOM" : "Evénement - DCOM",
    "Ex. approf. méthodo." : "Mathématiques élémentaires - Exercices approfondis et méthodologie",
    "Exercices de Calculus I" : "Calculus I - Exercices",
    "Géométrie dans plan & espace" : "Mathématiques élémentaires - Géométrie dans le plan et l'espace",
    "Inégalités" : "Mathématiques élémentaires - Inégalités",
    "Logique" : "Mathématiques élémentaires - Logique",
    "Mécanique - Théorie" : "Physique générale I - Théorie",
    "Mécanique - travaux dirigés" : "Physique générale I - TP",
    "Nombres complexes" : "Algèbre I",
    "ondes opt phys méca fluides t." : "Physique générale II",
    "Prog. et algo II." : "Programmation et algorithmique II",
    "Programmation et algorithmiq I" : "Programmation et algorithmique I",
    "Travaux dirigés algèbre I A" : "Côté d'algèbre I",
    "Travaux dirigés d'algèbre I B." : "Côté d'algèbre I",

    "Algèbre II": "Algèbre II",
    "Algèbre linéaire & géométrieII" : "Algèbre linéaire et géométrie II",
    "Bases de données I" : "Bases de données I", 
    "Bases de données I (Partie A)" : "Bases de données I", 
    "Bases de données I Partie B" : "Bases de données I", 
    "calcul tens et rel. rest." : "Calcul tensoriel et relativité restreinte",
    "Dvlpt. dirigé par modèles" : "Dévellopement dirigé par modèles", 
    "English for Science, part 1" : "English for science",
    "English for Science, part 2" : "English for science",
    "Fonct. ordinateurs" : "Fonctionnement des ordinateurs",
    "Form.LaTeX" : "Formation LaTeX",
    "Introd. analyse numérique" : "Introduction à l'analyse numérique",
    "Méca classique I" : "Mécanique classique I",
    "Modélisation logicielle" : "Modélisation logicielle", 
    "Physique générale III (A)" : "Physique Générale III",
    "Program.fonct." : "Programmation fonctionnelle",
    "Prob. stat. I (A)" : "Probabilité et statistique I",
    "Prob. stat. I (B)" : "Probabilité et statistique I",
    "Projet d'informatique": "Projet d'informatique",
    "Projet de dvlpt logiciel": "Projet de génie logiciel",
    "Sém. Introd. log. math. I": "Séminaire d'intro à la logique mathématique",
    "Sém.Intro.logique math. II": "Séminaire d'intro à la logique mathématique",
    "Simulation": "Simulation",
    "Structures de données I": "Structures de données I",
    "Théorie des groupes" : "Théorie des groupes",
    "Travaux pratiques d'analyse nu": "Travaux pratiques d'analyse numérique",
    "Univers struct. const." : "Univers",

    "Algèbre III" : "Algèbre III",
    "Anal. math. III (A)" : "Analyse mathématique III",
    "Anal.math. III (B)" : "Analyse mathématique III",
    "Analyse complexe" : "Analyse complexe",
    "Analyse et conc des syst d'ens" : "Analyse et conception des systèmes d'enseignement",
    "Bases de données II" : "Bases de données II",
    "Compilation" : "Compilation",
    "Compl de probabilités et stat" : "Complément de probabilité et statistiques",
    "Compléments de mathématiques" : "Compléments de mathématiques",
    "Dida ana. trans. sec-univ" : "Didactique de l'analyse dans la transition secondaire-université",
    "Economie - AAEP" : "Économie",
    "English for Sc Com part 1" : "English for Scientific Communication",
    "English for Sc Com part 2" : "English for Scientific Communication",
    "Etude d'obj. math élémentaire" : "Étude d'obets de la mathématique élémentaire",
    "Evénement - DCOM" : "Evénement - DCOM",
    "Intelligence artificielle" : "Intelligence artificielle",
    "Intro à la réalité fin - AAEP" : "Introduction à la réalité financière", 
    "introd à l'util bases don math" : "Introduction à l'utilisation de bases de données mathématiques",
    "Introd aux variétés différ." : "Introduction aux variétés différentielles",
    "Logique math." : "Logique mathématique",
    "Machine Learning I" : "Machine Learning I",
    "Méca. quant. applications" : "Mécanique quantique - applications", 
    "Méca. quant. théorie" : "Mécanique quantique - théorie", 
    "Mécanique Classique II" : "Mécanique classique II", 
    "Physique atom. et molé." : "Physique atomique et moléculaire",
    "Physique nucléaire I Theorie" : "Physique nucléaire",
    "Prob. et stat. II (A)" : "Probabilités et statistiques II", 
    "Prob. et stat. II (B)" : "Probabilités et statistiques II",
    "Projet de réseaux I" : "Projet de réseaux I",
    "Réseaux I" : "Réseaux I",
    "Sciences de l'éduc + formation": "Sciences de l'éducation et de la formation",
    "Sém logique math I" : "Séminaire d'introduction à la logique mathématiqu I",
    "Structures de données II" : "Structure de données II",
    "Systèmes d'exploitation" : "Systèmes d'exploitation",
    "TAF - AAEP" : "Théorie et analyse finnancière",
    "Théorie des modèles I" : "Théorie des modèles",

    "AdvDeepLearn" : "Advanced machine learning and deep learning", 
    "AdvMachLearn" : "Advanced machine learning and deep learning", 
    "AidMulticrDéc" : "Aide multicritère à la décision", 
    "Algorithmique et bioinfo" : "Algorithmique et bioinformatique", 
    "Analyse num : équations diff." : "Projet d'analyse numérique sur les équations différentielles", 
    "AtModélRechOp" : "Atelier de modélisation en Recherche Opérationnelle", 
    "Calcul.et complexité" : "Calculabilité et complexité", 
    "Defi IA" : "Défi en IA", 
    "Dida ana. trans. sec-univ" : "Didactique de l'analyse dans la transition secondaire-université", 
    "Didactique math.disc.connexes" : "Didactique des mathématiques discrètes", 
    "Entrepr, créativité - AAEP" : "Entrepreneuriat, créativité et modèles d'affaires",
    "Entrepre., busines plan - AAEP" : "Entrepreneuriat, business plan et plan financier", 
    "Etude d'obj. math élémentaire" : "Etude d'objets de la mathématique élémentaire", 
    "Finance d'entreprise - AAEP" : "Finance d'entreprise", 
    "Financial Markets - AAEP" : "Financial Markets and Portfolio Management",
    "Gest de la prod et mod - AAEP" : "Gestion de la production et modélisation",
    "Gestion financière - AAEP" : "Gestion financière",
    "Graphes et intelligence artifi" : "Graphes et intelligence artificielle",
    "GraphOptComb" : "Graphes et optimisation combinatoire",
    "introd à l'util bases don math" : "Introduction à l'utilisation de bases de données mathématiques",
    "Introduction à R" : "Introduction à R",
    "Knowledge repres.and reasoning" : "Knowledge representation and reasoning",
    "Machine Learning II" : "Machine Learning II",
    "Méth. formelles application" : "Methode formelle - application",
    "Méthodes formelles : Fondem." : "Methode formelle - fondements",
    "Méthodes formelles : intro" : "Methode formelle - introduction",
    "Méthodes statistiques" : "Méthodes statistiques",
    "Models and methods in Data Sci" : "Models and methods in Data Science",
    "OptimGestProd" : "Optimisation et gestion de la production",
    "OptmLin" : "Optimisation linéaire",
    "Produits fin. dérivés - AAEP" : "Prouits financiers dérivés",
    "Projet d'analyse math intro" : "Projet d'analyse mathématique - introduction",
    "Projet d'analyse math travaux" : "Projet d'analyse mathématique - introduction",
    "Projet géom.alg." : "Projet de géométrie algébrique",
    "Projet logique math. II" : "Projet de logique mathématique II", 
    "Projet Math. effectives" : "Projet de mathématiques effectives",
    "Projet prob.stat. III" : "Projet de probabilités et statistiques III", 
    "Questions de probabilités" : "Questions de probabilités", 
    "Réseaux II" : "Réseaux II",
    "Sém. gestion port. - AAEP" : "Séminaire de gestion de portefeuille",
    "SéminIntArtf" : "Séminaire Intelligence Artificielle",
    "Software evolution" : "Software evolution",
    "StreamDatAnal" : "Stream data analysis", 
}
