course_info = {
    "Aide à la réussite (partie A)" : ("Aide à la réussite","GREEN"),
    "Aide à la réussite (partie B)" : ("Aide à la réussite","GREEN"),
    "Aide à la réussite C." : ("Aide à la réussite","GREEN"),
    "Algèbre linéaire" : ("Mathématiques pour l'informatique - Algèbre linéaire","RED"),
    "Calculus I" : ("Calculus I - Théorie","RED"),
    "Elec et magné - TD & TP" : ("Physique générale II - TP","CYAN"),
    "Elec et magnétisme - Théorie" : ("Physique générale II - Théorie","CYAN"),
    "Eval. continue math. élém." : ("Mathématiques élémentaires - Evaluation continue","RED"),
    "Evénement - DCOM" : ("Evénement - DCOM","GREY"),
    "Ex. approf. méthodo." : ("Mathématiques élémentaires - Exercices approfondis et méthodologie","RED"),
    "Exercices de calculus I" : ("Calculus I - Exercices","RED"),
    "Fonct. ordinateurs" : ("Fonctionnement des ordinateurs","BLUE"),
    "Géométrie dans plan & espace" : ("Mathématiques élémentaires - Géométrie dans le plan et l'espace","RED"),
    "Inégalités" : ("Mathématiques élémentaires - Inégalités","RED"),
    "Logique" : ("Mathématiques élémentaires - Logique","RED"),
    "Mathématiques discrètes" : ("Mathématiques pour l'informatique - Mathématiques discrètes","RED"),
    "Mécanique - Théorie" : ("Physique générale I - Théorie","CYAN"),
    "Mécanique - travaux dirigés" : ("Physique générale I - TP","CYAN"),
    "Prog. et algo II." : ("Programmation et algorithmique II","BLUE"),
    "Programmation et algorithmiq I" : ("Programmation et algorithmique I","BLUE"),
    "Projet d'informatique" : ("Projet d'informatique","GREY"),

    "Bases de données I" : ("Bases de données I","BLUE"),
    "Bases de données I (Partie A)" : ("Bases de données I","BLUE"),
    "Bases de données I (Partie C)" : ("Bases de données I","BLUE"),
    "Bases de données I Partie B" : ("Bases de données I","BLUE"),
    "Calculus II" : ("Calculus II","RED"),
    "Dvlpt. dirigé par modèles" : ("Génie logiciel","BLUE"),
    "Economie politique - Partie 1" : ("Economie politique","ORANGE"),
    "Ecopol et tutorat 1 - AAEP" : ("Economie politique","ORANGE"),
    "Electronique" : ("Electronique","CYAN"),
    "English for Science, part 1" : ("English for science","GREY"),
    "English for Science, part 2" : ("English for science","GREY"),
    "Evénement - DCOM" : ("Evénement - DCOM","GREY"),
    "Form.LaTeX" : ("Formation LaTex","GREY"),
    "Matière à préciser" : ("Matière à préciser","GREY"),
    "Modélisation logicielle" : ("Génie logiciel","BLUE"),
    "Nombres complexes" : (" Nombres complexes","RED"),
    "OptmLin" : ("Optimisation","PURPLE"),
    "Probabilités" : ("Probabilités","RED"),
    "Projet anal. & concept. log." : ("Projet de génie logiciel","BLUE"),
    "Projet de dvlpt logiciel" : ("Projet de génie logiciel","BLUE"),
    "Projet de réseaux I" : ("Réseaux I - Projet","BLUE"),
    "Réseaux I" : ("Réseaux I","BLUE"),
    "Structures de données I" : ("Structures de données I","BLUE"),
    "Systèmes d'exploitation" : ("Systèmes d'exploitation","BLUE"),

    "Bases de données II" : ("Bases de données II","BLUE"),
    "Compilation" : ("Compilation","BLUE"),
    "Crypto sécurité info" : ("Cryptographie et sécurité des systèmes informatiques","BLUE"),
    "English for Sc Com part 1" : ("English for scientific communication","GREY"),
    "English for Sc Com part 2" : ("English for scientific communication","GREY"),
    "Evénement - DCOM" : ("Evénement - DCOM","GREY"),
    "GraphOptComb" : ("Graphes et optimisation combinatoire","PURPLE"),
    "Informatique temps-réel" : ("Informatique temps-réel","BLUE"),
    "Approches classiques IA" : ("Intelligence artificielle","BLUE"),
    "Intro à la compta" : ("Introduction à la comptabilité","ORANGE"),
    "Intro au Deep Learning" : ("Intro au Deep Learning","BLUE"),
    "Introduction à R" : ("Probabilités et statistique - Introduction à R","GREY"),
    "Machine Learning I" : ("Machine Learning I","BLUE"),
    "Probabilités et statistique" : ("Probabilités et statistique","GREY"),
    "Progr.logique" : ("Programmation logique","BLUE"),
    "Program.fonct." : ("Programmation fonctionnelle","BLUE"),
    "Séminaire d'informatique" : ("Séminaires d'informatique en gestion d'entreprise","BLUE"),
    "SignProces1" : ("Signal processing","PURPLE"),
    "Simulation" : ("Simulation","BLUE"),
    "Structures de données II" : ("Structures de données II","BLUE"),

    "Activité promotionnelle" : ("Activité promotionnelle","GREY"),
    "Advanced Operating Systems" : ("Advanced Operating Systems","BLUE"),
    "AdvDeepLearn" : ("Advanced Deep Learning","PURPLE"),
    "AdvMachLearn" : ("Advanced Machine Learning","PURPLE"),
    "AdvTopArtifIntel" : ("Advanced topics in Artificial Intelligence","BLUE"),
    "AidMulticrDéc" : ("Aide multicritère à la décision","BLUE"),
    "Algorithmique et bioinfo" : ("Algorithmique et BioInformatique","BLUE"),
    "AtModélRechOp" : ("Ateliers de modélisation en recherche opérationnelle","BLUE"),
    "AudioProces" : ("Audio Processing","PURPLE"),
    "Base de donnees Web et Web sem" : ("Base de données Web et Web sémantique","PURPLE"),
    "Calcul.et complexité" : ("Calculabilité et complexité","BLUE"),
    "Cloud and Edge Computing" : ("Cloud computing","BLUE"),
    "CommAnalNum" : ("Communications analogiques et numériques","PURPLE"),
    "CompetProgram" : ("Competitive programming","PURPLE"),
    "Compilation" : ("Compilation","BLUE"),
    "Computer Vision" : ("Computer Vision","PURPLE"),
    "Crypto sécurité info" : ("Cryptographie et sécurité des systèmes informatiques","BLUE"),
    "Cybersécurité" : ("Cybersécurité","BLUE"),
    "Deep Learning for Natural Lang" : ("Deep Learning for Natural Language and Sequence Processing","BLUE"),
    "Defi IA" : ("Défis en intelligence artificielle","BLUE"),
    "Ecolog. indus. et terri - AAEP" : ("Ecologie industrielle et territoriale","GREY"),
    "English for Sc Com part 1" : ("English for scientific communication Partie 1","GREY"),
    "English for Sc Com part 2" : ("English for scientific communication Partie 2","GREY"),
    "Entrepr, créativité - AAEP" : ("Entrepreneuriat, créativité et modèles d'affaires","GREY"),
    "Entrepre., busines plan - AAEP" : ("Entrepreneuriat, business plan et plan financier","GREY"),
    "Ethique droit de l'info" : ("Ethique et droit de l'informatique","GREY"),
    "Evénement - DCOM" : ("Evénement - DCOM","GREY"),
    "Graphes et intelligence artifi" : ("Graphes et intelligence artificielle","GREY"),
    "Informatique temps-réel" : ("Informatique temps-réel","GREY"),
    "Intro au calcul scientifique" : ("Introduction au calcul scientifique (Anum)","GREY"),
    "Knowledge repres.and reasoning" : ("Knowledge representation and reasoning","GREY"),
    "MachDeepLearnMultRetr" : ("Multimedia information retrieval","GREY"),
    "Machine Learning I" : ("Machine Learning I","GREY"),
    "Machine Learning II" : ("Machine Learning II","GREY"),
    "Mana et anal. des orga - AAEP" : ("Management et analyse des organisations","GREY"),
    "Matière à préciser" : ("Matière à préciser","GREY"),
    "MedImProc" : ("Medical image processing","GREY"),
    "Méth. formelles application" : ("Méthodes formelles pour la conception de systèmes : applications","GREY"),
    "Méthodes formelles : Fondem." : ("Méthodes formelles pour la conception de systèmes : fondements","GREY"),
    "Méthodes formelles : intro" : ("Méthodes formelles pour la conception de systèmes : fondements","GREY"),
    "Models and methods in Data Sci" : ("Models and methods in Data Sciences","GREY"),
    "MRH - AAEP" : ("Management des ressources humaines","GREY"),
    "Networks for Multimedia" : ("Networks for multimedia and the Internet of things","GREY"),
    "NetworkSecMan" : ("Network security and management","GREY"),
    "OptimGestProd" : ("Optimisation et gestion de la production","GREY"),
    "OptimNonLin" : ("Optimisation non linéaire","GREY"),
    "Philosophie sciences" : ("Philosophie des sciences","GREY"),
    "Progr.logique" : ("Programmation logique","GREY"),
    "ProjExpertDigLog" : ("Projet d'expertises digitale et logicielle","GREY"),
    "Réseaux II" : ("Réseaux II","GREY"),
    "Sciences et société" : ("Sciences et société","GREY"),
    "SDD III: explo & prediction" : ("Exploration et prédiction des données","GREY"),
    "Séminaire d'informatique" : ("Séminaires d'Informatique en gestion d'entreprise","GREY"),
    "SéminIntArtf" : ("Séminaire Intelligence Artificielle","GREY"),
    "SignProces1" : ("Signal processing","GREY"),
    "Simulation" : ("Simulation","GREY"),
    "Software evolution" : ("Software evolution","GREY"),
    "Travaux pratiques d'analyse nu" : ("TP Analyse numériques","GREY"),
    "VisProcesSmartSpac" : ("Visual processing and smart spaces","GREY")
}