color = {
    "Aide à la réussite A" : "GREEN",
    "Aide à la réussite B" : "GREEN",
    "Aide à la réussite C." : "GREEN",
    "Algèbre linéaire" : "RED",
    "Calculus I" : "RED",
    "Elec et magné - TD & TP" : "CYAN",
    "Elec et magnétisme - Théorie" : "CYAN",
    "Eval. continue math. élém." : "RED",
    "Evénement - DCOM" : "GREY",
    "Ex. approf. méthodo." : "RED",
    "Exercices de calculus I" : "RED",
    "Fonct. ordinateurs" : "BLUE",
    "Géométrie dans plan & espace" : "RED",
    "Inégalités" : "RED",
    "Logique" : "RED",
    "Mathématiques discrètes" : "RED",
    "Mécanique - Théorie" : "CYAN",
    "Mécanique - travaux dirigés" : "CYAN",
    "Prog. et algo II." : "BLUE",
    "Programmation et algorithmiq I" : "BLUE",
    "Projet d'informatique" : "GREY",

    "Bases de données I" : "BLUE",
    "Bases de données I (Partie A)" : "BLUE",
    "Bases de données I (Partie C)" : "BLUE",
    "Bases de données I Partie B" : "BLUE",
    "Calculus II" : "RED",
    "Dvlpt. dirigé par modèles" : "BLUE",
    "Economie politique - Partie 1" : "ORANGE",
    "Ecopol et tutorat 1 - AAEP" : "ORANGE",
    "Electronique" : "CYAN",
    "English for Science, part 1" : "GREY",
    "English for Science, part 2" : "GREY",
    "Evénement - DCOM" : "GREY",
    "Form.LaTeX" : "GREY",
    "Matière à préciser" : "GREY",
    "Modélisation logicielle" : "BLUE",
    "Nombres complexes" : "RED",
    "OptmLin" : "PURPLE",
    "Probabilités" : "RED",
    "Projet anal. & concept. log." : "BLUE",
    "Projet de dvlpt logiciel" : "BLUE",
    "Projet de réseaux I" : "BLUE",
    "Réseaux I" : "BLUE",
    "Structures de données I" : "BLUE",
    "Systèmes d'exploitation" : "BLUE",

    "Bases de données II" : "BLUE",
    "Compilation" : "BLUE",
    "Crypto sécurité info" : "BLUE",
    "English for Sc Com part 1" : "GREY",
    "English for Sc Com part 2" : "GREY",
    "Evénement - DCOM" : "GREY",
    "GraphOptComb" : "PURPLE",
    "Informatique temps-réel" : "BLUE",
    "Intelligence artificielle" : "BLUE",
    "Intro.à la comptabilité - AAEP" : "ORANGE",
    "Introduction à R" : "GREY",
    "Machine Learning I" : "BLUE",
    "Matière à préciser" : "GREY",
    "Probabilités et statistique" : "GREY",
    "Progr.logique" : "BLUE",
    "Program.fonct." : "BLUE",
    "Séminaire d'informatique" : "BLUE",
    "SignProces1" : "PURPLE",
    "Simulation" : "BLUE",
    "Structures de données II" : "BLUE",
    "Travaux pratiques d'analyse nu" : "BLUE",

    "Activité promotionnelle" : "GREY",
    "Advanced Operating Systems" : "BLUE",
    "AdvDeepLearn" : "PURPLE",
    "AdvMachLearn" : "PURPLE",
    "AdvTopArtifIntel" : "BLUE",
    "AidMulticrDéc" : "BLUE",
    "Algorithmique et bioinfo" : "BLUE",
    "AtModélRechOp" : "BLUE",
    "AudioProces" : "PURPLE",
    "Base de donnees Web et Web sem" : "BLUE",
    "Calcul.et complexité" : "BLUE",
    "Cloud and Edge Computing" : "BLUE",
    "CommAnalNum" : "PURPLE",
    "CompetProgram" : "GREY",
    "Compilation" : "GREY",
    "ComputVisMachInt" : "GREY",
    "Crypto sécurité info" : "GREY",
    "Cybersécurité" : "GREY",
    "Deep Learning for Natural Lang" : "GREY",
    "Defi IA" : "GREY",
    "Ecolog. indus. et terri - AAEP" : "GREY",
    "English for Sc Com part 1" : "GREY",
    "English for Sc Com part 2" : "GREY",
    "Entrepr, créativité - AAEP" : "GREY",
    "Entrepre., busines plan - AAEP" : "GREY",
    "Ethique droit de l'info" : "GREY",
    "Evénement - DCOM" : "GREY",
    "Graphes et intelligence artifi" : "GREY",
    "Informatique temps-réel" : "GREY",
    "Introd. analyse numérique" : "GREY",
    "Knowledge repres.and reasoning" : "GREY",
    "MachDeepLearnMultRetr" : "GREY",
    "Machine Learning I" : "GREY",
    "Machine Learning II" : "GREY",
    "Mana et anal. des orga - AAEP" : "GREY",
    "Matière à préciser" : "GREY",
    "MedImProc" : "GREY",
    "Méth. formelles application" : "GREY",
    "Méthodes formelles : Fondem." : "GREY",
    "Méthodes formelles : intro" : "GREY",
    "Models and methods in Data Sci" : "GREY",
    "MRH - AAEP" : "GREY",
    "Networks for Multimedia" : "GREY",
    "NetworkSecMan" : "GREY",
    "OptimGestProd" : "GREY",
    "OptimNonLin" : "GREY",
    "Philosophie sciences" : "GREY",
    "Progr.logique" : "GREY",
    "ProjExpertDigLog" : "GREY",
    "Réseaux II" : "GREY",
    "Sciences et société" : "GREY",
    "SDD III: explo & prediction" : "GREY",
    "Séminaire d'informatique" : "GREY",
    "SéminIntArtf" : "GREY",
    "SignProces1" : "GREY",
    "Simulation" : "GREY",
    "Software evolution" : "GREY",
    "Travaux pratiques d'analyse nu" : "GREY",
    "VisProcesSmartSpac" : "GREY"
}