course_math = {
    "Aide à la réussite A" : ("Aide à la réussite","GREEN"),
    "Aide à la réussite B" : ("Aide à la réussite","GREEN"),
    "Aide à la réussite C." : ("Aide à la réussite","GREEN"),
    "Aide à la réussite D." : ("Aide à la réussite", "GREEN"),
    "Calculus I" : ("Calculus I - Théorie","RED"),
    "Calculus II" : ("Calculus II","RED"),
    "Eval. continue math. élém." : ("Mathématiques élémentaires - Evaluation continue","RED"),
    "Evénement - DCOM" : ("Evénement - DCOM","GREY"),
    "Ex. approf. méthodo." : ("Mathématiques élémentaires - Exercices approfondis et méthodologie","RED"),
    "Exercices de calculus I" : ("Calculus I - Exercices","RED"),
    "Géométrie dans plan & espace" : ("Mathématiques élémentaires - Géométrie dans le plan et l'espace","RED"),
    "Inégalités" : ("Mathématiques élémentaires - Inégalités","RED"),
    "Logique" : ("Mathématiques élémentaires - Logique","RED"),
    "Mécanique - Théorie" : ("Physique générale I - Théorie","CYAN"),
    "Mécanique - travaux dirigés" : ("Physique générale I - TP","CYAN"),
    "Prog. et algo II." : ("Programmation et algorithmique II","BLUE"),
    "Programmation et algorithmiq I" : ("Programmation et algorithmique I","BLUE"),
    "Alg . lin. géom. I. A." : ("Algèbre linéaire et géométrie I", "RED"),
    "Alg . lin. géom. I. B" : ("Algèbre linéaire et géométrie I", "RED"),
    "Alg . lin. géom. I. C." : ("Algèbre linéaire et geométrie I", "RED"),
    "Algèbre I. A." : ("Algèbre I", "RED"),
    "Algèbre I. B." : ("Algèbre I", "RED"),
    "Analyse I (partie A)" : ("Analyse I", "RED"),
    "Analyse I B" : ("Analyse I", "RED"),
    "Elec et magnétisme - Théorie" : ("Electricité et magnétisme - Théorie", "CYAN"),
    "Electro et magné - travaux dir" : ("Electricité et magnétisme - Travaux dirigés", "CYAN"),

    "Activité promotionnelle" : ("Activité promotionnelle", "GREY"),
    "Algèbre II": ("Algèbre II", "RED"),
    "Algèbre linéaire & gaométrieII" : ("Algèbre linéaire et géométrie II", "RED"),
    "Analyse math. II (B)" : ("Analyse mathématique II", "RED"),
    "Analyse mathématique II (A)" : ("Analyse mathématique II", "RED"),
    "Bases de données I" : ("Bases de données I - Théorie", "BLUE"),
    "Bases de données I (partie A)" : ("Bases de données I - TP SQL", "BLUE"),
    "Bases de données I partie B" : ("Bases de données I - TP pratique", "BLUE"),
    "calcul tens et rel. rest." : ("Calcul tensoriel et relativité restreinte", "CYAN"),
    "Dvlpt. dirigé par modèles" : ("Dévellopement dirigé par modèles", "BLUE"),
    "English for Science, part 1" : ("English for science","GREY"),
    "English for Science, part 2" : ("English for science","GREY"),
    "Fonct. ordinateurs" : ("Fonctionnement des ordinateurs","BLUE"),
    "Form.LaTeX" : ("Formation LaTeX", "GREY"),
    "Introd. analyse numérique" : ("Introduction à l'analyse numérique", "RED"),
    "Méca classique I" : ("Mécanique classique I", "CYAN"),
    "Modélisation logicielle" : ("Modélisation logicielle", "BLUE"),
    "Physique Générale III (A)" : ("Physique Générale III", "CYAN"),
    "Program.fonct." : ("Programmation fonctionnelle", "BLUE"),
    "Prob. stat. I (A)" : ("Probabilité et statistique I", "RED"),
    "Prob. stat. I (B)" : ("Probabilité et statistique I", "RED"),
    "Projet d'informatique": ("Projet d'informatique", "BLUE"),
    "Projet de dvlpt logiciel": ("Projet GL", "BLUE"),
    "Sém. Introd. log. math. I": ("Séminaire d'intro à la logique mathématique I", "RED"),
    "Sém.Intro.logique math. II": ("Séminaire d'intro à la logique mathématique II", "RED"),
    "Simulation": ("Simulation", "BLUE"),
    "Structures de données I": ("Structures de données I", "BLUE"),
    "Théorie des groupes" : ("Théorie des groupes", "CYAN"),
    "Travaux pratiques d'analyse nu": ("Travaux pratiques d'analyse numérique", "RED"),
    "Univers struct. const." : ("Univers", "CYAN"),

    "Algèbre III" : ("Algèbre III", "RED"),
    "Anal. math. III (A)" : ("Analyse mathématique III", "RED"),
    "Anal.math. III (B)" : ("Analyse mathématique III", "RED"),
    "Analyse complexe" : ("Analyse complexe", "RED"),
    "Analyse et conc des syst d'ens" : ("Analyse et conception des systèmes d'enseignement", "GREY"),
    "Bases de données II" : ("Bases de données II", "BLUE"),
    "Compilation" : ("Compilation", "BLUE"),
    "Compl de probabilités et stat" : ("Complément de probabilité et statistiques", "RED"),
    "Compléments de mathématiques" : ("Compléments de mathématiques", "CYAN"),
    "Dida ana. trans. sec-univ" : ("Didactique de l'analyse dans la transition secondaire-université", "GREY"),
    "Economie - AAEP" : ("Économie", "ORANGE"),
    "English for Sc Com part 1" : ("English for Scientific Communication", "GREY"),
    "English for Sc Com part 2" : ("English for Scientific Communication", "GREY"),
    "Etude d'obj. math élémentaire" : ("Étude d'obets de la mathématique élémentaire", "RED"),
    "Evénement - DCOM" : ("Evénement - DCOM", "GREY"),
    "Intelligence artificielle" : ("Intelligence artificielle", "BLUE"),
    "Intro à la réalité fin - AAEP" : ("Introduction à la réalité financière", "ORANGE"),
    "introd à l'util bases don math" : ("Introduction à l'utilisation de bases de données mathématiques", "GREY"),
    "Introd aux variétés différ." : ("Introduction aux variétés différentielles", "RED"),
    "Logique math." : ("Logique mathématique", "RED"),
    "Machine Learning I" : ("Machine Learning I", "BLUE"),
    "Méca. quant. applications" : ("Mécanique quantique - applications", "CYAN"),
    "Méca. quant. théorie" : ("Mécanique quantique - théorie", "CYAN"),
    "Mécanique Classique II" : ("Mécanique classique II", "CYAN"),
    "Physique atom. et molé." : ("Physique atomique et moléculaire", "CYAN"),
    "Physique nucléaire I Theorie" : ("Physique nucléaire", "CYAN"),
    "Prob. et stat. II (A)" : ("Probabilités et statistiques II", "RED"),
    "Prob. et stat. II (B)" : ("Probabilités et statistiques II", "RED"),
    "Projet de réseaux I" : ("Projet de réseaux I", "BLUE"),
    "Réseaux I" : ("Réseaux I", "BLUE"),
    "Sciences de l'éduc + formation": ("Sciences de l'éducation et de la formation", "GREY"),
    "Sém logique math I" : ("Séminaire d'introduction à la logique mathématiqu I", "RED"),
    "Structures de données II" : ("Structure de données II", "BLUE"),
    "Systèmes d'exploitation" : ("Systèmes d'exploitation", "BLUE"),
    "TAF - AAEP" : ("Théorie et analyse finnancière", "ORANGE"),
    "Théorie des modèles I" : ("Théorie des modèles", "RED")

}
