course_info = {
    "Aide à la réussite (partie A)" : "Aide à la réussite",
    "Aide à la réussite (partie B)" : "Aide à la réussite",
    "Aide à la réussite C." : "Aide à la réussite",
    "Algèbre linéaire" : "Mathématiques pour l'informatique - Algèbre linéaire",
    "Calculus I" : "Calculus I - Théorie",
    "Elec et magné - TD & TP" : "Physique générale II - TP",
    "Elec et magnétisme - Théorie" : "Physique générale II - Théorie",
    "Eval. continue math. élém." : "Mathématiques élémentaires - Evaluation continue",
    "Evénement - DCOM" : "Evénement - DCOM",
    "Ex. approf. méthodo." : "Mathématiques élémentaires - Exercices approfondis et méthodologie",
    "Exercices de calculus I" : "Calculus I - Exercices",
    "Fonct. ordinateurs" : "Fonctionnement des ordinateurs",
    "Géométrie dans plan & espace" : "Mathématiques élémentaires - Géométrie dans le plan et l'espace",
    "Inégalités" : "Mathématiques élémentaires - Inégalités",
    "Logique" : "Mathématiques élémentaires - Logique",
    "Mathématiques discrètes" : "Mathématiques pour l'informatique - Mathématiques discrètes",
    "Mécanique - Théorie" : "Physique générale I - Théorie",
    "Mécanique - travaux dirigés" : "Physique générale I - TP",
    "Prog. et algo II." : "Programmation et algorithmique II",
    "Programmation et algorithmiq I" : "Programmation et algorithmique I",
    "Projet d'informatique" : "Projet d'informatique",

    "Bases de données I" : "Bases de données I",
    "Bases de données I (Partie A)" : "Bases de données I",
    "Bases de données I (Partie C)" : "Bases de données I",
    "Bases de données I Partie B" : "Bases de données I",
    "Calculus II" : "Calculus II",
    "Dvlpt. dirigé par modèles" : "Génie logiciel",
    "Economie politique - Partie 1" : "Economie politique",
    "Ecopol et tutorat 1 - AAEP" : "Economie politique",
    "Electronique" : "Electronique",
    "English for Science, part 1" : "English for science",
    "English for Science, part 2" : "English for science",
    "Evénement - DCOM" : "Evénement - DCOM",
    "Form.LaTeX" : "Formation LaTex",
    "Matière à préciser" : "Matière à préciser",
    "Modélisation logicielle" : "Génie logiciel",
    "Nombres complexes" : " Nombres complexes",
    "OptmLin" : "Optimisation",
    "Probabilités" : "Probabilités",
    "Projet anal. & concept. log." : "Projet de génie logiciel",
    "Projet de dvlpt logiciel" : "Projet de génie logiciel",
    "Projet de réseaux I" : "Réseaux I - Projet",
    "Réseaux I" : "Réseaux I",
    "Structures de données I" : "Structures de données I",
    "Systèmes d'exploitation" : "Systèmes d'exploitation",

    "Approches classiques IA" : "Intelligence artificielle",
    "Bases de données II" : "Bases de données II",
    "Compilation" : "Compilation",
    "Crypto sécurité info" : "Cryptographie et sécurité des systèmes informatiques",
    "English for Sc Com part 1" : "English for scientific communication",
    "English for Sc Com part 2" : "English for scientific communication",
    "Evénement - DCOM" : "Evénement - DCOM",
    "GraphOptComb" : "Graphes et optimisation combinatoire",
    "Informatique temps-réel" : "Informatique temps-réel",
    "Intro à la compta" : "Introduction à la comptabilité",
    "Intro au Deep Learning" : "Intelligence artificielle",
    "Introduction à R" : "Probabilités et statistique - Introduction à R",
    "Machine Learning I" : "Machine Learning I",
    "Probabilités et statistique" : "Probabilités et statistique",
    "Progr.logique" : "Programmation logique",
    "Program.fonct." : "Programmation fonctionnelle",
    "Séminaire d'informatique" : "Séminaires d'informatique en gestion d'entreprise",
    "SignProces1" : "Signal processing",
    "Simulation" : "Simulation",
    "Structures de données II" : "Structures de données II",

    "Advanced Operating Systems" : "Advanced Operating Systems",
    "AdvDeepLearn" : "Advanced Deep Learning",
    "AdvMachLearn" : "Advanced Machine Learning",
    "AdvTopArtifIntel" : "Advanced topics in Artificial Intelligence",
    "AidMulticrDéc" : "Aide multicritère à la décision",
    "AtModélRechOp" : "Ateliers de modélisation en recherche opérationnelle",
    "Calcul.et complexité" : "Calculabilité et complexité",
    "Cloud and Edge Computing" : "Cloud and Edge computing",
    "CommAnalNum" : "Communications analogiques et numériques",
    "CompetProgram" : "Competitive programming",
    "Compilation" : "Compilation",
    "Computer Vision" : "Computer Vision and Machine Intelligence",
    "Crypto sécurité info" : "Cryptographie et sécurité des systèmes informatiques",
    "Cybersécurité" : "Cybersécurité",
    "Deep Learning for Natural Lang" : "Deep Learning for Natural Language and Sequence Processing",
    "Defi IA" : "Défis en intelligence artificielle",
    "Ecolog. indus. et terri - AAEP" : "Ecologie industrielle et territoriale",
    "English for Sc Com part 1" : "English for scientific communication Partie 1",
    "English for Sc Com part 2" : "English for scientific communication Partie 2",
    "Entrepr, créativité - AAEP" : "Entrepreneuriat, créativité et modèles d'affaires",
    "Entrepre., busines plan - AAEP" : "Entrepreneuriat, business plan et plan financier",
    "Ethique droit de l'info" : "Ethique et droit de l'informatique",
    "Evénement - DCOM" : "Evénement - DCOM",
    "Graphes et intelligence artifi" : "Graphes et intelligence artificielle",
    "Informatique temps-réel" : "Informatique temps-réel",
    "Intro au calcul scientifique" : "Introduction au calcul scientifique",
    "Knowledge repres.and reasoning" : "Knowledge representation and reasoning",
    "MachDeepLearnMultRetr" : "Multimedia information retrieval",
    "Machine Learning I" : "Machine Learning I",
    "Machine Learning II" : "Machine Learning II",
    "Mana et anal. des orga - AAEP" : "Management et analyse des organisations",
    "MedImProc" : "Medical image processing",
    "Méth. formelles application" : "Méthodes formelles pour la conception de systèmes : applications",
    "Méthodes formelles : Fondem." : "Méthodes formelles pour la conception de systèmes : fondements",
    "Méthodes formelles : intro" : "Méthodes formelles pour la conception de systèmes : fondements",
    "Models and methods in Data Sci" : "Models and methods in Data Sciences",
    "MRH - AAEP" : "Management des ressources humaines",
    "Networks for Multimedia" : "Networks for multimedia and the Internet of things",
    "NetworkSecMan" : "Network security and management",
    "OptimGestProd" : "Optimisation et gestion de la production",
    "OptimNonLin" : "Optimisation non linéaire",
    "Philosophie sciences" : "Philosophie des sciences",
    "Progr.logique" : "Programmation logique",
    "ProjExpertDigLog" : "Projet d'expertises digitale et logicielle",
    "Réseaux II" : "Réseaux II",
    "Sciences et société" : "Sciences et société",
    "Séminaire d'informatique" : "Séminaires d'Informatique en gestion d'entreprise",
    "SéminIntArtf" : "Séminaire Intelligence Artificielle",
    "SignProces1" : "Signal processing",
    "Simulation" : "Simulation",
    "Software evolution" : "Software evolution",
    "VisProcesSmartSpac" : "Visual processing and smart spaces",
}